### ISSUE TITLE
Built-in help doesn't honour custom key bindings

### ISSUE THREAD

**Issue by lebensterben** [MitMaro/git-interactive-rebase-tool#212]
To reproduce this bug:
- Change key bindings in `~/.gitconfig`
- When `git-interactive-rebase-tool` is running, hit `?` and you'd see that your bindings are not correctly *shown* here, though they do *work*.

**Comment by MitMaro** [comment]
Thanks for the report!

Are you using version 1.1.0?

I think this has been fixed in master, which I hope will be released soon. I will verify that this does work.

**Comment by lebensterben** [comment]
>Thanks for the report! ...

@MitMaro I installed it via `cargo install`. Ans just now I built it on the master branch, still the problem persists.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MitMaro** [comment]
Hey @lebensterben !

I just ran a test with the latest master and everything seems to be working as expected.

I know this was a problem in a previous version of the tool, so my guess is that you have an older version that is running, even when you try to run the version from `master`.

### With Default Key Bindings

![girt-custom-keys-defaults](https://user-images.githubusercontent.com/177427/72210237-e29c8700-3492-11ea-8055-a10695921446.png)

![girt-custom-keys-defaults-2](https://user-images.githubusercontent.com/177427/72210248-f942de00-3492-11ea-9e13-58688a0b1c0d.png)

### With Custom Key Bindings

```
$ git config --global --get-regex 'interactive-rebase-tool'
interactive-rebase-tool.inputabort 1
interactive-rebase-tool.inputactionbreak 2
interactive-rebase-tool.inputactiondrop 3
interactive-rebase-tool.inputactionedit 4
interactive-rebase-tool.inputactionedit 6
interactive-rebase-tool.inputactionfixup 7
interactive-rebase-tool.inputactionpick 8
interactive-rebase-tool.inputactionreword 9
interactive-rebase-tool.inputactionsquash A
interactive-rebase-tool.inputconfirmno B
interactive-rebase-tool.inputconfirmyes C
interactive-rebase-tool.inputedit D
interactive-rebase-tool.inputforceabort E
interactive-rebase-tool.inputforcerebase F
interactive-rebase-tool.inputhelp G
interactive-rebase-tool.inputmovedown I
interactive-rebase-tool.inputmovestepdown H
interactive-rebase-tool.inputmoveleft J
interactive-rebase-tool.inputmoveright K
interactive-rebase-tool.inputmoveselectiondown L
interactive-rebase-tool.inputmoveselectionup M
interactive-rebase-tool.inputmoveup N
interactive-rebase-tool.inputmovestepup O
interactive-rebase-tool.inputopeninexternaleditor P
interactive-rebase-tool.inputrebase Q
interactive-rebase-tool.inputshowcommit R
interactive-rebase-tool.inputtogglevisualmode S
```

![girt-custom-keys](https://user-images.githubusercontent.com/177427/72210260-28594f80-3493-11ea-9040-7f76be190e02.png)

![girt-custom-keys-2](https://user-images.githubusercontent.com/177427/72210266-445cf100-3493-11ea-836b-eb387f32e30a.png)

**Comment by MitMaro** [comment]
I'm going to close the issue, but feel free to post more details/re-open if there is something else that can be done.

Thanks again for the report!

**Comment by MitMaro** [comment]
Oh! I almost forgot!

I did find two keybindings that were incorrectly documented in the README, I will correct those shortly!

**Comment by lebensterben** [comment]
I confirm that on the latest build from crates.io, the bug is fixed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
